FROM docker.io/library/ruby:3.4.9-alpine3.22
RUN apk add g++ musl-dev make libstdc++ imagemagick imagemagick-jpeg
WORKDIR /src
COPY Gemfile .
RUN bundle install
COPY . .
EXPOSE 4300
ENTRYPOINT ["bundle", "exec", "jekyll", "serve", "--host=0", "-w"]
