FROM docker.io/library/ruby:alpine
RUN apk add g++ musl-dev make libstdc++ imagemagick imagemagick-jpeg
WORKDIR /src
COPY Gemfile .
RUN bundle install
EXPOSE 4300
ENTRYPOINT ["bundle", "exec", "jekyll", "serve", "--host=0", "-w"]
